basePath: /api/v1alpha1
definitions:
  cluster.Cluster:
    properties:
      creationTime:
        type: string
      description:
        type: string
      name:
        type: string
    type: object
  cluster.Config:
    properties:
      config:
        type: string
    type: object
  cluster.CreateClusterRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  cluster.ListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/cluster.Cluster'
        type: array
      total:
        type: integer
    type: object
  cluster.UpdateClusterRequest:
    properties:
      description:
        type: string
    type: object
info:
  contact:
    email: 46617237@qq.com
    name: API Support
  description: This is a swagger for KubeLemon
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/majian159/kubelemon
  title: KubeLemon API
  version: "1.0"
paths:
  /namespaces/{namespace}/clusters:
    get:
      operationId: listClusters
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - in: query
        name: keywords
        type: string
      - default: 10
        in: query
        name: limit
        type: integer
      - default: 0
        in: query
        name: offset
        type: integer
      - in: query
        items:
          type: string
        name: sortBy
        type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cluster.ListResponse'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
        default:
          description: ""
          schema:
            $ref: '#/definitions/cluster.ListResponse'
      tags:
      - clusters
    post:
      operationId: postCluster
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: request
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.CreateClusterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cluster.Cluster'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
        default:
          description: ""
          schema:
            $ref: '#/definitions/cluster.Cluster'
      summary: Create cluster
      tags:
      - clusters
  /namespaces/{namespace}/clusters/{name}:
    delete:
      operationId: deleteCluster
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Cluster name
        in: path
        name: name
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a cluster
      tags:
      - clusters
    get:
      operationId: getCluster
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Cluster name
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cluster.Cluster'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
        default:
          description: ""
          schema:
            $ref: '#/definitions/cluster.Cluster'
      summary: Get cluster
      tags:
      - clusters
    patch:
      operationId: patchCluster
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Cluster name
        in: path
        name: name
        required: true
        type: string
      - description: request
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.UpdateClusterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cluster.Cluster'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
        default:
          description: ""
          schema:
            $ref: '#/definitions/cluster.Cluster'
      summary: Update cluster
      tags:
      - clusters
  /namespaces/{namespace}/clusters/{name}/config:
    get:
      operationId: getClusterConfig
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Cluster name
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cluster.Config'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
        default:
          description: ""
          schema:
            $ref: '#/definitions/cluster.Config'
      summary: Get cluster config
      tags:
      - clusters
    put:
      operationId: putClusterConfig
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Cluster name
        in: path
        name: name
        required: true
        type: string
      - description: config
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.Config'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
        default:
          description: ""
          schema:
            type: string
      summary: Put cluster config
      tags:
      - clusters
swagger: "2.0"
